spring:
  application:
    name: kafka
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: starwars-streams-app
      # ADICIONE ESTAS CONFIGURAÇÕES:
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        schema.registry.url: http://localhost:8081
      # Configuração do state store (opcional mas recomendado)
      state-dir: /tmp/kafka-streams
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
      group-id: starwars-consumer-group

starwars:
  topic: starwars-topic
swapi:
  url: https://swapi.dev/api/people/
image:
  url: https://starwars-databank-server.vercel.app/api/v1/characters/name/

logging:
  level:
    com:
      br:
        kafka:
          services:
            esterno: DEBUG
            kafka:
              consumidor:
                ServicoConsumidorPersonagemStarWars: DEBUG
#    org:
#      apache:
#        kafka:
#          streams: DEBUG
cors:
  originPatterns: "http://localhost:8080,http://localhost:3000,http://localhost:8090,http://192.168.100.93:3000,https://www.erosmonitoramento.com.br,https://erosmonitoramento.com.br"